### PR TITLE
Installed Lint, updated code, moved screens to screens folder

### PR DESCRIPTION
**Pull request by jospape-newdays**
Install code linting.

`make validate` validate your code if it complies with the standard code styling

### CODE REVIEW

**Comment by sanderroosendaal** [comment]
Somehow you broke WelcomeScreen: Uncaught TypeError: Cannot read properties of undefined (reading 'props')

**Comment by sanderroosendaal** [comment]
In the makefile, you are running npm. I usually run expo start. is that a problem? I don't know

**Comment by j-pape** [comment]
> you are running npm. I usually run expo start. is that a pro

`expo` is used to run/build/test the program. `npm` is used to update/install packages.
we also use `npm` to run commands like lint to validate code styling

**Comment by j-pape** [comment]
> Somehow you broke WelcomeScreen: Uncaught TypeError: Cannot read properties of undefined (reading 'props')

Fixed that using the babel/eslint-parser

**Pull request merged**
